### C
[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c', 'cpp']
hook_add = '''
let g:clang_c_completeopt   = 'menuone,preview'
let g:clang_cpp_completeopt = 'menuone,preview'
let g:clang_dotfile = '.clang_complete'
let g:clang_auto = 0
let g:clang_complete_auto = 0
let g:clang_auto_select = 0
let g:clang_use_library = 1
let g:clang_library_path="/usr/local/lib"
let g:clang_c_options = '-std=c11'
let g:clang_cpp_options = '-std=c++1z -stdlib=libc++ --pedantic-errors'

'''

[[plugins]]
repo = 'vim-scripts/nginx.vim'
on_ft = ['nginx']

### C++ highlighter
[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['cpp']
hook_add = '''
let g:cpp_class_scope_highlight = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_concepts_highlight = 1
let g:cpp_experimental_template_highlight = 1
'''

### Markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md']
hook_add = '''
let g:vim_markdown_toc_autofit = 1
'''

### Go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
let g:go_list_type = "quickfix"
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"
let g:go_fmt_autosave = 0
let g:go_def_mapping_enabled = 0
'''

[[plugins]]
repo = 'dgryski/vim-godef'
on_ft = ['go']

### toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

### HTML,CSS,Javascript
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo = 'wavded/vim-stylus'
on_ft = ['stylus']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'typescript', 'javascript.jsx', 'jsx', 'tsx']

[[plugins]]
repo =  'leafgarland/typescript-vim'
on_ft = ['javascript', 'typescript', 'javascript.jsx', 'jsx', 'tsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'typescript', 'javascript.jsx', 'jsx', 'tsx']
hook_add = '''
let g:vim_jsx_pretty_colorful_config = 1
'''

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo =  'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'typescript', 'javascript.jsx']
hook_add = '''
let b:javascript_lib_use_react = 1
'''

[[plugins]]
repo =  'othree/es.next.syntax.vim'
on_ft = ['javascript', 'typescript', 'javascript.jsx']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['javascript', 'typescript', 'vue']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['ts', 'typescript']

[[plugins]]
repo = 'Quramy/tsuquyomi'
depends = ['vimproc.vim']
on_ft = ['typescript']
hook_add = '''
let g:tsuquyomi_completion_detail = 1
'''

[[plugins]]
repo = 'Quramy/tsuquyomi-vue'
on_ft = ['javascript', 'typescript', 'vue']

[[plugins]]
repo = 'Quramy/vim-js-pretty-template'

repo = 'rust-lang/rust.vim'
on_ft = ['rs', 'rust']

# [[plugins]]
# repo = 'racer-rust/vim-racer'
# on_ft = 'rust'
# hook_add = '''
# let g:racer_cmd = $HOME.'/.cargo/bin/racer'
# let g:racer_experimental_completer = 1
# au FileType rust nmap gd <Plug>(rust-doc)
# au FileType rust nmap gs <Plug>(rust-def-vertical)
# '''

[[plugins]]
repo = 'koka831/python-syntax'
on_ft = 'python'
hook_add = '''
let g:python_highlight_all = 1
'''

# [[plugins]]
# repo = 'davidhalter/jedi-vim'
# on_ft = 'python'
# hook_add = '''
# let g:jedi#documentation_command = "gd"
# '''

[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = 'python'

# [[plugins]]
# repo = 'plytophogy/vim-virtualenv'
# on_ft = 'python'
# depends = ['jedi-vim']

# [[plugins]]
# repo = 'andviro/flake8-vim'
# on_ft = 'python'

[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = 'elixir'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']
hook_add = '''
let g:haskell_enable_quantification = 1   " to enable highlighting of `forall`
let g:haskell_enable_recursivedo = 1      " to enable highlighting of `mdo` and `rec`
let g:haskell_enable_arrowsyntax = 1      " to enable highlighting of `proc`
let g:haskell_enable_pattern_synonyms = 1 " to enable highlighting of `pattern`
let g:haskell_enable_typeroles = 1        " to enable highlighting of type roles
let g:haskell_enable_static_pointers = 1  " to enable highlighting of `static`
let g:haskell_backpack = 1 
'''

[[plugins]]
repo = 'kana/vim-filetype-haskell'
on_ft = ['haskell']

[[plugins]]
repo = 'dag/vim2hs'
on_ft = ['haskell']

# ruby
# [[plugins]]
# repo = 'marcus/rsense'
# on_ft = ['ruby']

# [[plugins]]
# repo = 'vim-ruby/vim-ruby'
# on_ft = ['ruby']

[[plugins]]
repo = 'lifepillar/pgsql.vim'
on_ft = ['sql']
hook_add = '''
let g:sql_type_default = 'pgsql'
'''
